### ISSUE TITLE
Out of stock

### ISSUE THREAD

**Issue by matthew73210** [velijv/nesp#1]
Hey,

[https://fr.aliexpress.com/item/1005004438528608.html?gatewayAdapt=glo2fra](lcd) is out of stock, do you happen to know of any others that work ?

Cheers

**Comment by velijv** [comment]
Sorry no, I recommend reading [the thread](https://community.home-assistant.io/t/esphome-nest-thermostat-clone-on-cheap-rotary-display/563296) - there are better options out there. I can sell you mine.
